### ISSUE TITLE
how to resolve such error during compile cpp2 lib? "TypeError: No registered converter was able to produce a C++ rvalue ...."

### ISSUE THREAD

**Issue by smarengin** [facebook/fbthrift#143]
It report following error during compiling lib/cpp2, would anybody can give me some advice?

......
make[3]: Leaving directory '/home/lyq/rcnn/thpp/3rdparty/fbthrift/thrift/lib/cpp'
Making all in cpp2
make[3]: Entering directory '/home/lyq/rcnn/thpp/3rdparty/fbthrift/thrift/lib/cpp2'
PYTHONPATH=../../.python-local/lib/python /usr/bin/python -mthrift_compiler.main --gen cpp2 Sasl.thrift
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/home/lyq/rcnn/thpp/3rdparty/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg/thrift_compiler/**init**.py", line 1, in <module>
    import generate
  File "/home/lyq/rcnn/thpp/3rdparty/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg/thrift_compiler/generate/**init**.py", line 21, in <module>
    import t_generator
  File "/home/lyq/rcnn/thpp/3rdparty/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg/thrift_compiler/generate/t_generator.py", line 23, in <module>
    from thrift_compiler import frontend
TypeError: No registered converter was able to produce a C++ rvalue of type std::string from this Python object of type str
Makefile:2111: recipe for target 'gen-cpp2/Sasl_types.h' failed
make[3]: **\* [gen-cpp2/Sasl_types.h] Error 1
.........

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
