### ISSUE TITLE
cpp2 compilation error when using "extends"

### ISSUE THREAD

**Issue by newpoo** [facebook/fbthrift#158]
We can reproduce it with the following simple example.

root@78f6e8b951ae:/cosmos/aperture/thrift# cat ./admin.thrift
# namespace cpp2 admin

service Admin {
}
root@78f6e8b951ae:/cosmos/aperture/thrift# cat ./aperture.thrift
include "admin.thrift"
namespace cpp2 aperture
service Aperture extends admin.Admin {
}
root@78f6e8b951ae:/cosmos/aperture/thrift# python -mthrift_compiler.main -r --gen cpp2 -o ./ ./aperture.thrift
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"_main_", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/usr/local/lib/python2.7/dist-packages/thrift_compiler/main.py", line 260, in <module>
main()
File "/usr/local/lib/python2.7/dist-packages/thrift_compiler/main.py", line 257, in main
conf.process(params)
File "/usr/local/lib/python2.7/dist-packages/thrift_compiler/main.py", line 240, in process
frontend.process(params, generate_wrapper)
File "/usr/local/lib/python2.7/dist-packages/thrift_compiler/main.py", line 238, in generate_wrapper
self.generate(*args)
File "/usr/local/lib/python2.7/dist-packages/thrift_compiler/main.py", line 213, in generate
inc.out_path = program.out_path
Boost.Python.ArgumentError: Python argument types in
None.None(t_program, str)
did not match C++ signature:
None(t_program
{lvalue}
, std::string, bool)
root@78f6e8b951ae:/cosmos/aperture/thrift#

**Comment by roticv** [comment]
My uneducated guess (I haven't tested our my hypothesis) is that the reason is because you commented out the namespace cpp2.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
