### ISSUE TITLE
build faild with anaconda3 environment

### ISSUE THREAD

**Issue by KazukiMorozumi** [facebook/fbthrift#221]
fbthrift build failed using this script.
https://github.com/facebook/fblualib/blob/master/install_all.sh

This error is related to python, so I guess anaconda cases this error.
How can I fix this?

#### environment
- OS: ubuntu 16.04
- gcc: 5.4.0
- g++: 5.4.0
- anaconda3 4.3.1

#### console output
```
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying thrift_py.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thrift_py.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thrift_py.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thrift_py.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thrift_py.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/thrift_py-0.9.0-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Creating /fbthrift/thrift/.python-local/lib/python/site.py
Processing thrift_py-0.9.0-py3.5.egg
creating /fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py3.5.egg
Extracting thrift_py-0.9.0-py3.5.egg to /fbthrift/thrift/.python-local/lib/python
Adding thrift-py 0.9.0 to easy-install.pth file

Installed /fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py3.5.egg
Processing dependencies for thrift-py==0.9.0
Finished processing dependencies for thrift-py==0.9.0
make[4]: Leaving directory '/fbthrift/thrift/compiler/py'
make[3]: Leaving directory '/fbthrift/thrift/compiler'
make[2]: Leaving directory '/fbthrift/thrift/compiler'
Making all in lib
make[2]: Entering directory '/fbthrift/thrift/lib'
Making all in thrift
make[3]: Entering directory '/fbthrift/thrift/lib/thrift'
PYTHONPATH=../../.python-local/lib/python /opt/conda/bin/python -mthrift_compiler.main --gen cpp2 frozen.thrift
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py3.5.egg/thrift_compiler/__init__.py", line 1, in <module>
    import generate
ImportError: No module named 'generate'
make[3]: *** [gen-cpp2/frozen_types.h] Error 1
Makefile:817: recipe for target 'gen-cpp2/frozen_types.h' failed
make[3]: Leaving directory '/fbthrift/thrift/lib/thrift'
make[2]: *** [all-recursive] Error 1
Makefile:416: recipe for target 'all-recursive' failed
make[2]: Leaving directory '/fbthrift/thrift/lib'
make[1]: *** [all-recursive] Error 1
Makefile:498: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/fbthrift/thrift'
Makefile:430: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by eduardo-elizondo** [comment]
Thrift now supports cmake. Go to the main directory and read the CMakeLists.txt for dependencies. Docs will be coming soon. 
For now build by doing:
cmake .
make
If you are using MacOSX you need to specify:
cmake -DOPENSSL_ROOT_DIR=path/to/openssl .
make

**Comment by ilovin** [comment]
but it cannot generate python module `thrift_compiler`
